/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dwi.aulia.anugerah_202102359_uas_perpustakaan;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class form_utama extends javax.swing.JFrame {

    /**
     * Creates new form form_utama
     */
    public form_utama() {
        initComponents();
        Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width,screen.height);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        tampil_tb_anggota();
        tampil_tb_buku();
        tampil_tb_peminjaman();
        Tanggal_sekarang();
        jamDigital();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Peminjaman = new javax.swing.JPanel();
        txt_cari_peminjaman = new javax.swing.JTextField();
        btn_cari_peminjaman = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_peminjaman = new javax.swing.JTable();
        btn_edit_peminjaman = new javax.swing.JButton();
        btn_edit_peminjaman1 = new javax.swing.JButton();
        data_buku = new javax.swing.JPanel();
        txt_cari_buku = new javax.swing.JTextField();
        btn_cari_buku = new javax.swing.JButton();
        btn_edit_buku = new javax.swing.JButton();
        btn_edit_buku1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_buku = new javax.swing.JTable();
        data_anggota = new javax.swing.JPanel();
        txt_cari_anggota = new javax.swing.JTextField();
        btn_cari_anggota = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_anggota = new javax.swing.JTable();
        btn_edit_anggota = new javax.swing.JButton();
        btn_edit_anggota1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pengaturan = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 204, 204));

        jLabel1.setText("Aplikasi Perpustakaan [UAS]");

        jLabel2.setText("Dwi Aulia Anugerah // 202102359 // UAS");

        lbl_jam.setText("JAM");

        lbl_tanggal.setText("TANGGAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_jam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tanggal)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_jam)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_tanggal))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Peminjaman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peminjaman", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txt_cari_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_peminjamanActionPerformed(evt);
            }
        });

        btn_cari_peminjaman.setText("Cari");
        btn_cari_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_peminjamanActionPerformed(evt);
            }
        });

        tb_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Anggota", "Nama", "Jurusan", "Kode Buku", "Judul Buku", "Tanggal Terbit", "Tanggal Pinjam"
            }
        ));
        jScrollPane2.setViewportView(tb_peminjaman);

        btn_edit_peminjaman.setText("Input Data Peminjaman");
        btn_edit_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_peminjamanActionPerformed(evt);
            }
        });

        btn_edit_peminjaman1.setText("Reset");
        btn_edit_peminjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_peminjaman1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeminjamanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_cari_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari_peminjaman))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(PeminjamanLayout.createSequentialGroup()
                        .addComponent(btn_edit_peminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit_peminjaman1)))
                .addContainerGap())
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_peminjaman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_peminjaman)
                    .addComponent(btn_edit_peminjaman1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peminjaman", Peminjaman);

        data_buku.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Buku", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txt_cari_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_bukuActionPerformed(evt);
            }
        });

        btn_cari_buku.setText("Cari");
        btn_cari_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_bukuActionPerformed(evt);
            }
        });

        btn_edit_buku.setText("Input Data Buku");
        btn_edit_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_bukuActionPerformed(evt);
            }
        });

        btn_edit_buku1.setText("Reset");
        btn_edit_buku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_buku1ActionPerformed(evt);
            }
        });

        tb_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Tanggal Terbit", "Pengarang"
            }
        ));
        jScrollPane5.setViewportView(tb_buku);

        javax.swing.GroupLayout data_bukuLayout = new javax.swing.GroupLayout(data_buku);
        data_buku.setLayout(data_bukuLayout);
        data_bukuLayout.setHorizontalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_bukuLayout.createSequentialGroup()
                        .addGap(0, 422, Short.MAX_VALUE)
                        .addComponent(txt_cari_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari_buku))
                    .addGroup(data_bukuLayout.createSequentialGroup()
                        .addComponent(btn_edit_buku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit_buku1)))
                .addContainerGap())
            .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(data_bukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        data_bukuLayout.setVerticalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_buku))
                .addGap(186, 186, 186)
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_buku)
                    .addComponent(btn_edit_buku1))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(data_bukuLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Data Buku", data_buku);

        data_anggota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Anggota", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txt_cari_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_anggotaActionPerformed(evt);
            }
        });

        btn_cari_anggota.setText("Cari");
        btn_cari_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_anggotaActionPerformed(evt);
            }
        });

        tb_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Anggota", "Nama", "Tempat Lahir", "Tanggal Lahir", "Jurusan", "Tanggal Masuk"
            }
        ));
        jScrollPane4.setViewportView(tb_anggota);

        btn_edit_anggota.setText("Input Data Anggota");
        btn_edit_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_anggotaActionPerformed(evt);
            }
        });

        btn_edit_anggota1.setText("Reset");
        btn_edit_anggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_anggota1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_anggotaLayout = new javax.swing.GroupLayout(data_anggota);
        data_anggota.setLayout(data_anggotaLayout);
        data_anggotaLayout.setHorizontalGroup(
            data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_anggotaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_cari_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari_anggota))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(data_anggotaLayout.createSequentialGroup()
                        .addComponent(btn_edit_anggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit_anggota1)))
                .addContainerGap())
        );
        data_anggotaLayout.setVerticalGroup(
            data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_anggotaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_anggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(data_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_anggota)
                    .addComponent(btn_edit_anggota1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Anggota", data_anggota);

        jMenu1.setText("File");

        pengaturan.setText("Pengaturan");
        jMenu1.add(pengaturan);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void btn_edit_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_peminjamanActionPerformed
        // TODO add your handling code here:
        new form_entry_peminjaman(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btn_edit_peminjamanActionPerformed

    private void btn_edit_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_bukuActionPerformed
        // TODO add your handling code here:
        new form_entry_buku(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btn_edit_bukuActionPerformed

    private void btn_edit_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_anggotaActionPerformed
        // TODO add your handling code here:
        new form_entry_anggota(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btn_edit_anggotaActionPerformed

    private void btn_edit_peminjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_peminjaman1ActionPerformed
        // TODO add your handling code here:
        tampil_tb_peminjaman();
    }//GEN-LAST:event_btn_edit_peminjaman1ActionPerformed

    private void btn_edit_buku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_buku1ActionPerformed
        // TODO add your handling code here:
        tampil_tb_buku();
    }//GEN-LAST:event_btn_edit_buku1ActionPerformed

    private void btn_edit_anggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_anggota1ActionPerformed
        // TODO add your handling code here:
        tampil_tb_anggota();
    }//GEN-LAST:event_btn_edit_anggota1ActionPerformed

    private void txt_cari_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_peminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_peminjamanActionPerformed

    private void btn_cari_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_peminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_peminjamanActionPerformed

    private void txt_cari_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_bukuActionPerformed
        // TODO add your handling code here:
        pencarian_buku();
    }//GEN-LAST:event_txt_cari_bukuActionPerformed

    private void btn_cari_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_bukuActionPerformed
        // TODO add your handling code here:
        pencarian_buku();
    }//GEN-LAST:event_btn_cari_bukuActionPerformed

    private void txt_cari_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_anggotaActionPerformed
        // TODO add your handling code here:
        pencarian_anggota();
    }//GEN-LAST:event_txt_cari_anggotaActionPerformed

    private void btn_cari_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_anggotaActionPerformed
        // TODO add your handling code here:
        pencarian_anggota();
    }//GEN-LAST:event_btn_cari_anggotaActionPerformed

    //pencarian data anggota
    public void pencarian_anggota(){
        String cari = txt_cari_anggota.getText();
        //String to=jCombo.getItemAt(i).toString();
        
       Object[] Baris={"No Bp","Nama","Tempat Lahir","Tanggal Lhair","Jurusan","Tanggal Masuk"};
       tabmode = new DefaultTableModel(null, Baris);
       tb_anggota.setModel(tabmode);

       //panggil method koneksi
       Connection koneksi = new koneksi_2().getConnection();
       
       //untuk menampilkan di table
       try{
           String sql="Select * from tb_mahasiswa where "
                   + "no_bp like '%"+cari+"%' "
                   + "OR nama like '%"+cari+"%' "
                   + "OR tempat_lahir like '%"+cari+"%' "
                   + "OR tanggal_lahir like '%"+cari+"%' "
                   + "OR jurusan like '%"+cari+"%' "
                   + "OR tanggal_masuk like '%"+cari+"%' "
                   + "order by no_bp asc";
           java.sql.Statement stmt=koneksi.createStatement();
           java.sql.ResultSet rslt=stmt.executeQuery(sql);
           while(rslt.next()){
               String no_bp=rslt.getString("no_bp");
               String nama=rslt.getString("nama");
               String tempat_lahir=rslt.getString("tempat_lahir");
               String tanggal_lahir=rslt.getString("tanggal_lahir");
               String jurusant=rslt.getString("jurusan");
               String tanggal_masuk=rslt.getString("tanggal_masuk");
               String[] dataField={no_bp,nama,tempat_lahir,tanggal_lahir,jurusant,tanggal_masuk};
               tabmode.addRow(dataField);
           }
       }
       catch(Exception ex){
       }
    }
    
    //pencarian data buku
    public void pencarian_buku(){
        String cari = txt_cari_buku.getText();
        Object[] Baris={"Kode Buku","Judul Buku","Tanggal Terbit","Pengarang"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_buku.setModel(tabmode);

        Connection koneksi = new koneksi_2().getConnection();
        try{
            String sql="Select * from tb_buku where kode_buku like '%"+cari+"%' or judul_buku like '%"+cari+"%' or tanggal_terbit like '%"+cari+"%' or pengarang like '%"+cari+"%' order by kode_buku asc";
            java.sql.Statement stmt=koneksi.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                String kode_buku=rslt.getString("kode_buku");
                String judul_buku=rslt.getString("judul_buku");
                String tanggal_terbit=rslt.getString("tanggal_terbit");
                String pengarang=rslt.getString("pengarang");
                String[] dataField={kode_buku,judul_buku,tanggal_terbit,pengarang};
                tabmode.addRow(dataField);
            }
        }
        catch(Exception ex){
        }
    }
    public void pencarian_peminjaman(){
        
    }

//perintah menampilkan tanggal
    public void Tanggal_sekarang(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("dd-MM-yyyy") ;
        lbl_tanggal.setText("Tanggal "+kal.format(sekarang));
    }
    
    // jam digital Konstruktor
  public void jamDigital() {
    // ActionListener untuk Keperluan Timer
    ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilai_jam <= 9) {
          // Tambahkan "0" didepannya
          nol_jam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilai_menit <= 9) {
          // Tambahkan "0" didepannya
          nol_menit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilai_detik <= 9) {
          // Tambahkan "0" didepannya
          nol_detik = "0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        // Menampilkan pada Layar
        lbl_jam.setText("Jam "+jam + ":" + menit + ":" + detik);
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();
  }
  
    private DefaultTableModel tabmode;
    //private String[] label = {"Username","Nama","Jenis Kelamin","Tempat Lahir","Tanggal Lahir","Alamat"};
    
    public void tampil_tb_buku(){
        Object []baris = {"Kode Buku","Judul Buku","Tanggal Terbit","Pengarang"};
        tabmode = new DefaultTableModel(null, baris);
        tb_buku.setModel(tabmode);
        Connection con = new koneksi_2().getConnection();
        try {
            String sql = "select * from tb_buku order by kode_buku asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String kode_buku = hasil.getString("kode_buku");
                String judul_buku = hasil.getString("judul_buku");
                String tanggal_terbit = hasil.getString("tanggal_terbit");
                String pengarang = hasil.getString("pengarang");
                String[] data = {kode_buku, judul_buku, tanggal_terbit, pengarang};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void tampil_tb_peminjaman(){
        Object []baris = {"No Bp","Nama","Jurusan","Kode Buku","Judul Buku","Tanggal Terbit","Tanggal Pinjam"};
        tabmode = new DefaultTableModel(null, baris);
        tb_peminjaman.setModel(tabmode);
        Connection con = new koneksi_2().getConnection();
        try {
            String sql = "select * from tb_peminjaman order by no_bp asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_bp = hasil.getString("no_bp");
                String nama = hasil.getString("nama");
                String jurusan = hasil.getString("jurusan");
                String kode_buku = hasil.getString("kode_buku");
                String judul_buku = hasil.getString("judul_buku"); 
                String tanggal_terbit = hasil.getString("tanggal_terbit");
                String tanggal_pinjam = hasil.getString("tanggal_pinjam");
                String[] data = {no_bp, nama, jurusan, kode_buku, judul_buku, tanggal_terbit, tanggal_pinjam};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //menampilkan data dari datatabe ke tabel
    public void tampil_tb_anggota(){
        Object []baris = {"No. Anggota","Nama","Tempat Lahir","Tanggal Lhair","Jurusan","Tanggal Masuk"};
        tabmode = new DefaultTableModel(null, baris);
        tb_anggota.setModel(tabmode);
        Connection con = new koneksi_2().getConnection();
        try {
            String sql = "select * from tb_anggota order by no_bp asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_bp = hasil.getString("no_bp");
                String nama = hasil.getString("nama");
                String tempat_lahir = hasil.getString("tempat_lahir");
                String tanggal_lahir = hasil.getString("tanggal_lahir");
                String jurusan = hasil.getString("jurusan"); 
                String tanggal_masuk = hasil.getString("tanggal_masuk");
                String[] data = {no_bp, nama, tempat_lahir, tanggal_lahir, jurusan, tanggal_masuk};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JButton btn_cari_anggota;
    private javax.swing.JButton btn_cari_buku;
    private javax.swing.JButton btn_cari_peminjaman;
    private javax.swing.JButton btn_edit_anggota;
    private javax.swing.JButton btn_edit_anggota1;
    private javax.swing.JButton btn_edit_buku;
    private javax.swing.JButton btn_edit_buku1;
    private javax.swing.JButton btn_edit_peminjaman;
    private javax.swing.JButton btn_edit_peminjaman1;
    private javax.swing.JPanel data_anggota;
    private javax.swing.JPanel data_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JMenuItem pengaturan;
    private javax.swing.JTable tb_anggota;
    private javax.swing.JTable tb_buku;
    private javax.swing.JTable tb_peminjaman;
    private javax.swing.JTextField txt_cari_anggota;
    private javax.swing.JTextField txt_cari_buku;
    private javax.swing.JTextField txt_cari_peminjaman;
    // End of variables declaration//GEN-END:variables

}
